// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package posts

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PostsComment struct {
	ID        int64              `json:"id"`
	PostID    int64              `json:"post_id"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	AuthorID  int64              `json:"author_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
