// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package posts

import (
	"context"
)

type Querier interface {
	AddComment(ctx context.Context, arg AddCommentParams) (PostsComment, error)
	GetComment(ctx context.Context, id int64) (PostsComment, error)
	GetComments(ctx context.Context, arg GetCommentsParams) ([]PostsComment, error)
}

var _ Querier = (*Queries)(nil)
