// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package posts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addComment = `-- name: AddComment :one
INSERT INTO posts.comments (
    post_id,
    author_id,
    parent_id,
    text
)
VALUES ($1, $2,
        $3, $4)
RETURNING id, post_id, parent_id, author_id, text, created_at, updated_at
`

type AddCommentParams struct {
	PostID   int64       `json:"post_id"`
	AuthorID int64       `json:"author_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	Text     string      `json:"text"`
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (PostsComment, error) {
	row := q.db.QueryRow(ctx, addComment,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.Text,
	)
	var i PostsComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, post_id, parent_id, author_id, text, created_at, updated_at
FROM posts.comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (PostsComment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i PostsComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComments = `-- name: GetComments :many
SELECT id, post_id, parent_id, author_id, text, created_at, updated_at
FROM posts.comments
WHERE post_id = $1
  AND parent_id IS NOT DISTINCT FROM $2
ORDER BY created_at ASC
LIMIT $4 OFFSET $3
`

type GetCommentsParams struct {
	PostID   int64       `json:"post_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) GetComments(ctx context.Context, arg GetCommentsParams) ([]PostsComment, error) {
	rows, err := q.db.Query(ctx, getComments,
		arg.PostID,
		arg.ParentID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostsComment
	for rows.Next() {
		var i PostsComment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
