// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package posts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPost = `-- name: AddPost :one
INSERT INTO posts.posts (
    author_id,
    title,
    text,
    comments_enabled
)
VALUES ($1, $2,
        $3, $4)
RETURNING id, author_id, title, text, comments_enabled, created_at, updated_at
`

type AddPostParams struct {
	AuthorID        int64  `json:"author_id"`
	Title           string `json:"title"`
	Text            string `json:"text"`
	CommentsEnabled bool   `json:"comments_enabled"`
}

type AddPostRow struct {
	ID              int64              `json:"id"`
	AuthorID        int64              `json:"author_id"`
	Title           string             `json:"title"`
	Text            string             `json:"text"`
	CommentsEnabled bool               `json:"comments_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AddPost(ctx context.Context, arg AddPostParams) (AddPostRow, error) {
	row := q.db.QueryRow(ctx, addPost,
		arg.AuthorID,
		arg.Title,
		arg.Text,
		arg.CommentsEnabled,
	)
	var i AddPostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, author_id, title, text, comments_enabled, created_at, updated_at
FROM posts.posts
WHERE id = $1
`

type GetPostRow struct {
	ID              int64              `json:"id"`
	AuthorID        int64              `json:"author_id"`
	Title           string             `json:"title"`
	Text            string             `json:"text"`
	CommentsEnabled bool               `json:"comments_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPost(ctx context.Context, id int64) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostForUpdate = `-- name: GetPostForUpdate :one
SELECT id, author_id, title, text, comments_enabled, created_at, updated_at
FROM posts.posts
WHERE id = $1
FOR UPDATE
`

type GetPostForUpdateRow struct {
	ID              int64              `json:"id"`
	AuthorID        int64              `json:"author_id"`
	Title           string             `json:"title"`
	Text            string             `json:"text"`
	CommentsEnabled bool               `json:"comments_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPostForUpdate(ctx context.Context, id int64) (GetPostForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPostForUpdate, id)
	var i GetPostForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, author_id, title, text, comments_enabled, created_at, updated_at
FROM posts.posts
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetPostsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type GetPostsRow struct {
	ID              int64              `json:"id"`
	AuthorID        int64              `json:"author_id"`
	Title           string             `json:"title"`
	Text            string             `json:"text"`
	CommentsEnabled bool               `json:"comments_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error) {
	rows, err := q.db.Query(ctx, getPosts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Text,
			&i.CommentsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByAuthor = `-- name: GetPostsByAuthor :many
SELECT id, author_id, title, text, comments_enabled, created_at, updated_at
FROM posts.posts
WHERE author_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetPostsByAuthorParams struct {
	AuthorID int64 `json:"author_id"`
	Offset   int32 `json:"offset"`
	Limit    int32 `json:"limit"`
}

type GetPostsByAuthorRow struct {
	ID              int64              `json:"id"`
	AuthorID        int64              `json:"author_id"`
	Title           string             `json:"title"`
	Text            string             `json:"text"`
	CommentsEnabled bool               `json:"comments_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPostsByAuthor(ctx context.Context, arg GetPostsByAuthorParams) ([]GetPostsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, getPostsByAuthor, arg.AuthorID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByAuthorRow
	for rows.Next() {
		var i GetPostsByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Text,
			&i.CommentsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommentsEnabled = `-- name: SetCommentsEnabled :one
UPDATE posts.posts
SET comments_enabled = $1
WHERE id = $2
RETURNING id, author_id, title, text, comments_enabled, created_at, updated_at
`

type SetCommentsEnabledParams struct {
	CommentsEnabled bool  `json:"comments_enabled"`
	ID              int64 `json:"id"`
}

type SetCommentsEnabledRow struct {
	ID              int64              `json:"id"`
	AuthorID        int64              `json:"author_id"`
	Title           string             `json:"title"`
	Text            string             `json:"text"`
	CommentsEnabled bool               `json:"comments_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetCommentsEnabled(ctx context.Context, arg SetCommentsEnabledParams) (SetCommentsEnabledRow, error) {
	row := q.db.QueryRow(ctx, setCommentsEnabled, arg.CommentsEnabled, arg.ID)
	var i SetCommentsEnabledRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
