// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package posts

import (
	"context"
)

type Querier interface {
	AddPost(ctx context.Context, arg AddPostParams) (AddPostRow, error)
	GetPost(ctx context.Context, id int64) (GetPostRow, error)
	GetPostForUpdate(ctx context.Context, id int64) (GetPostForUpdateRow, error)
	GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error)
	GetPostsByAuthor(ctx context.Context, arg GetPostsByAuthorParams) ([]GetPostsByAuthorRow, error)
	SetCommentsEnabled(ctx context.Context, arg SetCommentsEnabledParams) (SetCommentsEnabledRow, error)
}

var _ Querier = (*Queries)(nil)
