package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"posts-service/internal/controller/graphql/converter"
	"posts-service/internal/entity"
	"posts-service/pkg/generated/posts/graphql/model"
)

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	comment, err := r.commentService.CreateComment(ctx, &entity.Comment{
		PostID:   input.PostID,
		AuthorID: input.AuthorID,
		ParentID: input.ParentID,
		Text:     input.Text,
	})
	if err != nil {
		return nil, err
	}
	return converter.ToGraphQLComment(comment), err
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID int64, parentID *int64, limit int, offset int) ([]*model.Comment, error) {
	comments, err := r.commentService.GetComments(ctx, postID, parentID, limit, offset)
	if err != nil {
		return nil, err
	}
	return converter.ToGraphQLComments(comments), err
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id int64) (*model.Comment, error) {
	comment, err := r.commentService.GetComment(ctx, id)
	if err != nil {
		return nil, err
	}
	return converter.ToGraphQLComment(comment), err
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int64) (<-chan *model.Comment, error) {
	comments, unsubscribe := r.commentSub.Subscribe(ctx, postID)

	out := make(chan *model.Comment, 1)

	go func() {
		defer close(out)
		defer unsubscribe()

		for {
			select {
			case <-ctx.Done():
				return

			case comment, ok := <-comments:
				if !ok {
					return
				}

				select {
				case out <- converter.ToGraphQLComment(comment):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}
