package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"posts-service/internal/controller/graphql/converter"
	"posts-service/internal/entity"
	"posts-service/pkg/generated/posts/graphql/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	commentsEnabled := true
	if input.CommentsEnabled != nil && !(*input.CommentsEnabled) {
		commentsEnabled = false
	}
	post, err := r.postService.CreatePost(ctx, &entity.Post{
		AuthorID:        input.AuthorID,
		Title:           input.Title,
		Text:            input.Text,
		CommentsEnabled: commentsEnabled,
	})
	if err != nil {
		return nil, err
	}
	return converter.ToGraphQLPost(post), nil
}

// SetPostCommentsEnabled is the resolver for the setPostCommentsEnabled field.
func (r *mutationResolver) SetPostCommentsEnabled(ctx context.Context, postID int64, authorID int64, enabled bool) (*model.Post, error) {
	post, err := r.postService.SetPostCommentsEnabled(ctx, postID, authorID, enabled)
	if err != nil {
		return nil, err
	}
	return converter.ToGraphQLPost(post), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, authorID *int64, limit int, offset int) ([]*model.Post, error) {
	posts, err := r.postService.GetPosts(ctx, authorID, limit, offset)
	if err != nil {
		return nil, err
	}
	return converter.ToGraphQLPosts(posts), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int64) (*model.Post, error) {
	post, err := r.postService.GetPost(ctx, id)
	if err != nil {
		return nil, err
	}
	return converter.ToGraphQLPost(post), nil
}
